// Custom sidebar generator that lets upstream `_category_.json` files
// opt categories into "section header" rendering:
//
//   {
//     "label": "FEATURES",
//     "position": 10,
//     "customProps": { "sidebarHeader": true }
//   }
//
// A category marked `sidebarHeader: true` is *not* rendered as a
// collapsible category. Instead, it becomes:
//   1. an HTML divider showing the category label, followed by
//   2. its children spliced into the same level as siblings.
//
// This gives us the all-caps decorative section dividers (ABOUT /
// FEATURES / REFERENCES) on top of an otherwise plain autogenerated
// sidebar — and lets upstream maintainers control the entire sidebar
// structure (page order, categories, AND top-level dividers) from
// frontmatter + `_category_.json` alone, with no per-product hand-
// written sidebar config in this repo.

// Self-contained types: Docusaurus does not re-export
// `NormalizedSidebarItem` / `SidebarItemsGeneratorOption` from its
// public package surface. Importing from deep `lib/...` paths breaks
// across version bumps, so we define the shape we touch here.
type SidebarItem =
  | {type: 'doc' | 'ref'; id: string; label?: string; customProps?: Record<string, unknown>}
  | {type: 'link'; href: string; label: string; customProps?: Record<string, unknown>}
  | {type: 'html'; value: string; defaultStyle?: boolean; customProps?: Record<string, unknown>}
  | {
      type: 'category';
      label: string;
      items: SidebarItem[];
      collapsed?: boolean;
      collapsible?: boolean;
      link?: unknown;
      customProps?: Record<string, unknown>;
    };

// Minimal shape of the per-doc metadata Docusaurus passes to a
// `sidebarItemsGenerator` (`SidebarItemsGeneratorDoc` is not re-exported
// from the public package surface — same reasoning as the types above).
type GeneratorDoc = {id: string; frontMatter?: Record<string, unknown>};

type GeneratorOption = (args: {
  defaultSidebarItemsGenerator: (a: unknown) => Promise<SidebarItem[]>;
  docs?: GeneratorDoc[];
  [key: string]: unknown;
}) => Promise<SidebarItem[]>;

function isSectionHeader(item: SidebarItem): boolean {
  return item.type === 'category' && item.customProps?.sidebarHeader === true;
}

function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, c => ({
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#39;',
  })[c] as string);
}

function flatten(
  items: SidebarItem[],
  enterpriseOnly: ReadonlySet<string>,
): SidebarItem[] {
  const out: SidebarItem[] = [];
  for (const item of items) {
    if (item.type === 'category') {
      const transformedChildren = flatten(item.items, enterpriseOnly);
      if (isSectionHeader(item)) {
        out.push({
          type: 'html',
          value: `<span class="sidebar-group-label">${escapeHtml(item.label)}</span>`,
          defaultStyle: true,
        });
        out.push(...transformedChildren);
      } else {
        out.push({...item, items: transformedChildren});
      }
    } else if (
      (item.type === 'doc' || item.type === 'ref') &&
      enterpriseOnly.has(item.id)
    ) {
      // Carry the opt-in flag onto the sidebar item so the swizzled
      // DocSidebarItem/Link can render the "Enterprise only" marker.
      out.push({
        ...item,
        customProps: {...item.customProps, enterpriseOnly: true},
      });
    } else {
      out.push(item);
    }
  }
  return out;
}

export const sectionHeaderSidebarGenerator: GeneratorOption = async ({
  defaultSidebarItemsGenerator,
  ...args
}) => {
  const items = await defaultSidebarItemsGenerator(args);
  // A page opts into the sidebar "Enterprise only" marker with an
  // `enterprise_only: true` frontmatter key (authored upstream, like
  // `dup:`). Explicit opt-in — NOT derived from the absence of `dup:`.
  const docs = (args.docs as GeneratorDoc[] | undefined) ?? [];
  const enterpriseOnly = new Set(
    docs.filter(d => d.frontMatter?.enterprise_only === true).map(d => d.id),
  );
  return flatten(items, enterpriseOnly);
};
