/**
 * Marketing extras appended to the bottom of every single blog post:
 *
 *   1. Product CTA banner — drives readers toward OvenMediaEngine
 *      (get-started + GitHub star) so the blog earns its keep as a
 *      top-of-funnel surface.
 *   2. "You might also like" — three related posts, scored by tag
 *      overlap with the current post (falling back to most-recent).
 *   3. "View all posts" link back to /blog.
 *
 * Data source: src/data/blog-index.json, regenerated by
 * scripts/build-blog-index.py whenever blog frontmatter changes.
 */

import React, {type ReactNode} from 'react';
import Link from '@docusaurus/Link';
import {useBlogPost} from '@docusaurus/plugin-content-blog/client';
import blogIndex from '@site/src/data/blog-index.json';

import styles from './PostFooterExtras.module.css';

type IndexedPost = {
  slug: string;
  permalink: string;
  title: string;
  description: string;
  tags: string[];
  date: string;
  dir: string;
};

const ALL_POSTS = blogIndex as IndexedPost[];

function pickRelated(
  currentSlug: string,
  currentTags: string[],
  limit = 3,
): IndexedPost[] {
  const currentTagSet = new Set(currentTags);

  const scored = ALL_POSTS
    .filter((p) => p.slug !== currentSlug)
    .map((p) => {
      const overlap = p.tags.filter((t) => currentTagSet.has(t)).length;
      return {post: p, score: overlap};
    });

  // Sort by tag overlap desc, then by date desc as tiebreaker so
  // posts with no shared tags still fall back to "most recent".
  scored.sort((a, b) => {
    if (b.score !== a.score) return b.score - a.score;
    return b.post.date.localeCompare(a.post.date);
  });

  return scored.slice(0, limit).map((s) => s.post);
}

function formatShortDate(iso: string): string {
  if (!iso) return '';
  return new Intl.DateTimeFormat('en', {
    month: 'short',
    year: 'numeric',
    timeZone: 'UTC',
  }).format(new Date(iso));
}

function ProductCTA(): ReactNode {
  return (
    <aside className={styles.cta} aria-labelledby="cta-heading">
      <div className={styles.ctaText}>
        <p className={styles.ctaEyebrow}>Build with OvenMediaEngine</p>
        <h3 id="cta-heading" className={styles.ctaTitle}>
          Sub-second latency streaming, open source.
        </h3>
        <p className={styles.ctaBody}>
          Live streaming with WebRTC, LL-HLS and SRT — production-ready,
          GPU accelerated, and free to self-host.
        </p>
      </div>
      <div className={styles.ctaActions}>
        <Link
          to="/ome"
          className={`${styles.ctaButton} ${styles.ctaButtonPrimary}`}>
          Get started
        </Link>
        <Link
          to="https://github.com/OvenMediaLabs/OvenMediaEngine"
          className={`${styles.ctaButton} ${styles.ctaButtonGhost}`}>
          ★ Star on GitHub
        </Link>
      </div>
    </aside>
  );
}

function RelatedPosts({posts}: {posts: IndexedPost[]}): ReactNode {
  if (posts.length === 0) return null;
  return (
    <section className={styles.related} aria-labelledby="related-heading">
      <header className={styles.relatedHeader}>
        <h3 id="related-heading" className={styles.relatedTitle}>
          You might also like
        </h3>
        <Link to="/blog" className={styles.viewAll}>
          View all posts →
        </Link>
      </header>
      <ul className={styles.relatedGrid}>
        {posts.map((p) => (
          <li key={p.slug} className={styles.relatedItem}>
            <Link to={p.permalink} className={styles.relatedCard}>
              <span className={styles.relatedMeta}>
                {formatShortDate(p.date)}
                {p.tags[0] && (
                  <>
                    <span className={styles.relatedDot}>·</span>
                    <span>{p.tags[0]}</span>
                  </>
                )}
              </span>
              <span className={styles.relatedCardTitle}>{p.title}</span>
              {p.description && (
                <span className={styles.relatedCardExcerpt}>
                  {p.description}
                </span>
              )}
            </Link>
          </li>
        ))}
      </ul>
    </section>
  );
}

export default function PostFooterExtras(): ReactNode {
  const {metadata} = useBlogPost();
  const tagLabels = metadata.tags.map((t) => {
    // The frontmatter tag value is the last segment of the permalink
    // (e.g. `/blog/tags/llhls` -> `llhls`). That matches what
    // build-blog-index.py stores in tags[].
    return t.permalink.split('/').filter(Boolean).pop() ?? '';
  });

  const related = pickRelated(metadata.frontMatter.slug ?? '', tagLabels, 3);

  return (
    <div className={styles.wrapper}>
      <ProductCTA />
      <RelatedPosts posts={related} />
    </div>
  );
}
