import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// The sidebar tree is fully derived from the synced upstream `docs/ome/`
// folder: file frontmatter `sidebar_position:` orders pages, and each
// subfolder's `_category_.json` controls its label, position, and
// landing page. Page authors edit upstream only — nothing here.
//
// The single hand-written entry below is the section title rendered
// above the autogenerated tree.
const sidebars: SidebarsConfig = {
  omeSidebar: [
    {type: 'html', value: "<span class=\"sidebar-manual-title\"><picture><source srcset=\"/images/airen_bi/OME_Text_W.svg\" type=\"image/svg+xml\" /><img src=\"/images/airen_bi/OME_Text_W.png\" alt=\"OvenMediaEngine\" style=\"height:20px;width:auto;display:block;\" /></picture></span>", defaultStyle: true},
    {type: 'autogenerated', dirName: '.'},
  ],
};

export default sidebars;
