import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// The sidebar tree is fully derived from the synced upstream
// `docs/ovenplayer/` folder. File frontmatter `sidebar_position:`
// orders pages; each subfolder's `_category_.json` controls its
// label, position, and landing page. Decorative section dividers
// (API Reference / Examples) come from `_category_.json` files that
// carry `customProps.sidebarHeader: true` — see
// `src/lib/sidebar-section-headers.ts` for the transform.
//
// Page authors edit upstream only; this file does not need touching.
const sidebars: SidebarsConfig = {
  ovenplayerSidebar: [
    {type: 'html', value: "<span class=\"sidebar-manual-title\"><picture><source srcset=\"/images/airen_bi/OP_Text_W.svg\" type=\"image/svg+xml\" /><img src=\"/images/airen_bi/OP_Text_W.png\" alt=\"OvenPlayer\" style=\"height:20px;width:auto;display:block;\" /></picture></span>", defaultStyle: true},
    {type: 'autogenerated', dirName: '.'},
  ],
};

export default sidebars;
