import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// The sidebar tree is fully derived from the synced upstream
// `docs/ome-enterprise/` folder. File frontmatter `sidebar_position:`
// orders pages; each subfolder's `_category_.json` controls its
// label, position, and landing page. Top-level decorative section
// dividers (ABOUT / PRE-BUILT PACKAGE INSTALLATION / ENTERPRISE ONLY
// / FEATURES / REFERENCES) come from `_category_.json` files that
// carry `customProps.sidebarHeader: true` — see
// `src/lib/sidebar-section-headers.ts` for the transform.
//
// Page authors edit upstream only; this file does not need touching.
const sidebars: SidebarsConfig = {
  omeEnterpriseSidebar: [
    {type: 'html', value: "<span class=\"sidebar-manual-title\">OvenMediaEngine Enterprise</span>", defaultStyle: true},
    {type: 'autogenerated', dirName: '.'},
  ],
};

export default sidebars;
